apiVersion: v1
kind: Pod
metadata:
  name: jkapp
  namespace: default
  labels:
    app.kubernetes.io/name: jkapp
spec:
  containers:
  - name: jkapp
    image: nginx:latest
    ports:
      - containerPort: 80
