on:
  push:

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: matrix job
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "hello world"

# pahle job ko run karne do and agar wo successful tab tu chal ja
# needs, continue on error, if: always
