on:
  push:

jobs:
  my_first_job:
    name: first job
    runs-on: ubuntu-slim
    steps:
      - run: echo "my first job ran successful"
  my_second_job:
    name: second job
    runs-on: ubuntu-slim
    steps:
      - run: echo "my second job ran successful"
