name: github action trigger practice
on:
  push:
    branches:
      - main
  pull_request:
     branches:
       - develop
       - main


jobs:
  terraform_init_plan:
    name: Terraform Init and Plan
    runs-on: ubuntu-latest
    steps:
      - name: terraform init
        run: terraform init
        
      - name: terraform validate
        run: terraform validate

      - run: terraform plan
